services:
  back-end:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    image: softy-pinko-back-end:task6

  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    image: softy-pinko-front-end:task6
    depends_on:
      - back-end

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
